# -*- coding: utf-8 -*-
"""EDA and Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2EORA77aIodt9-9MBI-jCXmabbrU7uJ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from scipy import stats

pd.set_option('display.max_columns', None)

df = pd.read_csv("/content/Employee Data.csv")   # change if needed
df.head()

# basic info
df.info()

# stats
df.describe(include='all')

# unique values & length
for col in df.columns:
    print(col, ":", df[col].nunique(), "unique values")
    print(df[col].unique())
    print()

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.head()

df.isnull().sum()
df['age'] = df['age'].replace(0, np.nan)
df = df.drop_duplicates()
numeric_cols = df.select_dtypes(include=['int64','float64']).columns
z = np.abs(stats.zscore(df[numeric_cols], nan_policy='omit'))
df_out = df[(z < 3).all(axis=1)]

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

"""Data Analysis"""

filtered = df[(df['age'] > 40) & (df['salary'] < 5000)]
filtered

#Plot Age vs Salary
sns.scatterplot(data=df, x='age', y='salary')
plt.title("Age vs Salary")
plt.show()

#People count by place
place_count = df['place'].value_counts()
sns.barplot(x=place_count.index, y=place_count.values)
plt.xticks(rotation=45)
plt.title("Count of People by Place")
plt.show()

le = LabelEncoder()

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

df_encoded = pd.get_dummies(df, drop_first=True)

scaler_std = StandardScaler()
scaler_mm = MinMaxScaler()

scaled_std = scaler_std.fit_transform(df_encoded)
scaled_mm = scaler_mm.fit_transform(df_encoded)

df_std = pd.DataFrame(scaled_std, columns=df_encoded.columns)
df_mm = pd.DataFrame(scaled_mm, columns=df_encoded.columns)

"""## Summary

- Performed EDA and explored unique values and statistics
- Cleaned the dataset by fixing missing values, removing duplicates and invalid age entries
- Detected and treated outliers
- Filtered and visualized key relationships (Age vs Salary and People by Place)
- Encoded categorical features into numeric form
- Scaled the data using StandardScaler and MinMaxScaler
- Final dataset is ready for machine learning applications

"""

